# Simple Home Network Configuration
# Perfect for basic home networks with minimal complexity

server:
  listen_addresses: ["0.0.0.0:67"]
  enable_logging: true
  enable_security: false
  max_leases: 100

subnets:
  - name: "home"
    network: "192.168.1.0"
    prefix_length: 24
    range_start: "192.168.1.100"
    range_end: "192.168.1.200"
    gateway: "192.168.1.1"
    dns_servers: ["192.168.1.1", "8.8.8.8"]
    domain_name: "home.local"
    lease_time: 86400
    max_lease_time: 172800
